Ensure that something was entered for GitHub email

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -33,8 +33,15 @@ else
   echo "==> What email address do you use with your GitHub account?"
 
   read github_email </dev/tty || {
-    github_email=null
+    github_email=""
   }
+
+  if [[ $github_email == "" ]]; then
+    echo "==> ERROR! An email address is required."
+    echo "==>        Re-run this script to try again."
+    echo
+    exit 1
+  fi
 
   # From: https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
   echo "==> Generating SSH key for $github_email …"
